### PR TITLE
Write Unit Tests Using Jest

### PR DESCRIPTION
**Pull request by anewman15**
In this PR,
I wrote unit tests using Jest for Project and Todo class methods

### CODE REVIEW

**Review by Forison — CHANGES_REQUESTED** [review]
## Status::Changes required
# 🙋‍♂️ @anewman15 
#### You have done a great job on this one so far, however there are a few changes we have to make the project approved.
* [x] Update the readme to include commands or steps to run the test.
* [x] I could not see the test on `addUpdatedTodoToProject` in the addtodo class, kindly add it.
* [x] All function ought to be tested as required in the project requirement. I realized that you skipped testing DOM, It is challenging in testing the DOM, but for sake of the requirement let us do it. [check this resource for guide](https://jestjs.io/docs/en/tutorial-jquery). Let us add test for the `dom_module` and `event_listener.js`
#### That is it, kindly make the change and submit a re-review.
#### Happy coding
Addo Forison

**Comment by anewman15** [comment]
@forison

This project is about **Unit** Testing. DOM manipulation and localStorage is **Integration** testing.

**Review by Dandush03 — CHANGES_REQUESTED** [review]
# Status: :red_circle: Require Changes :red_circle: 

## Please make sure on your next review to integrated the feature request below from @Forison which I quote;
- [x] I could not see the test on addUpdatedTodoToProject in the addtodo class, kindly add it.
- [x] All function ought to be tested as required in the project requirement. I realized that you skipped testing DOM, It is challenging in testing the DOM, but for sake of the requirement let us do it. check this resource for guide. Let us add test for the dom_module and event_listener.js.

## Regards, and Happy Coding

**Comment by anewman15** [comment]
Hi @Dandush03,

This project is **not** about integration testing. This is about Unit testing. Hence, I will not make the changes requested. Screenshot of specs is attached
unit-test

**Review by christianotieno — APPROVED** [review]
## Project Approved 🍾 
Hello @anewman15 👋 

I trust you are doing great. 
From my assessment, I can see your test suites are covering the required units in this codebase.  The tests are passing and have covered the possible scenarios for this project. I will go ahead and mark this as complete. 👍 

I wish you all the very best in your next tasks. 🥇 

### Happy coding 💻 

#### Christian Otieno(TSE)

**Comment by anewman15** [comment]
Now, that's awesome! Thanks @christianotieno!

@Forison @Dandush03

**Pull request merged**
